Remove Dev Docker as it's not necessary for one dev

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,7 +2,11 @@
 
 echo "Running Pre-Commit"
 
-pnpm run lint
+if !pnpm run lint; then
+    echo "Lint failed"
+    exit 1
+end
+
 pnpm run format
 pnpm run test:unit
 
